"""add provenance column to artifacts

Revision ID: 3a1c350217d9
Revises: 744ef0c92771
Create Date: 2026-04-06 20:30:17.178807

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a1c350217d9'
down_revision: Union[str, Sequence[str], None] = '744ef0c92771'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artifacts', sa.Column('provenance', sa.Text(), nullable=True), schema='catalog')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('artifacts', 'provenance', schema='catalog')
    # ### end Alembic commands ###
