"""initial schema

Revision ID: 744ef0c92771
Revises: 
Create Date: 2026-04-05 15:39:18.729341

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '744ef0c92771'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artifacts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('source_museum', sa.String(), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('source_id', sa.String(), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('object_type', sa.String(), nullable=True),
    sa.Column('materials', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('dimensions', sa.Text(), nullable=True),
    sa.Column('period', sa.String(), nullable=True),
    sa.Column('dynasty', sa.String(), nullable=True),
    sa.Column('ruler_id', sa.String(), nullable=True),
    sa.Column('ruler_display_name', sa.String(), nullable=True),
    sa.Column('date_start', sa.Integer(), nullable=True),
    sa.Column('date_end', sa.Integer(), nullable=True),
    sa.Column('date_display', sa.String(), nullable=True),
    sa.Column('origin_site_id', sa.String(), nullable=True),
    sa.Column('origin_site_display_name', sa.String(), nullable=True),
    sa.Column('origin_site_raw', sa.Text(), nullable=True),
    sa.Column('origin_certainty', sa.String(), nullable=True),
    sa.Column('excavation_id', sa.String(), nullable=True),
    sa.Column('tomb_temple_id', sa.String(), nullable=True),
    sa.Column('current_location', sa.String(), nullable=True),
    sa.Column('accession_number', sa.String(), nullable=True),
    sa.Column('credit_line', sa.Text(), nullable=True),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('thumbnail_url', sa.Text(), nullable=True),
    sa.Column('license', sa.String(), nullable=False),
    sa.Column('wikidata_id', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='catalog'
    )
    op.create_index(op.f('ix_catalog_artifacts_dynasty'), 'artifacts', ['dynasty'], unique=False, schema='catalog')
    op.create_index(op.f('ix_catalog_artifacts_excavation_id'), 'artifacts', ['excavation_id'], unique=False, schema='catalog')
    op.create_index(op.f('ix_catalog_artifacts_object_type'), 'artifacts', ['object_type'], unique=False, schema='catalog')
    op.create_index(op.f('ix_catalog_artifacts_origin_site_id'), 'artifacts', ['origin_site_id'], unique=False, schema='catalog')
    op.create_index(op.f('ix_catalog_artifacts_period'), 'artifacts', ['period'], unique=False, schema='catalog')
    op.create_index(op.f('ix_catalog_artifacts_ruler_id'), 'artifacts', ['ruler_id'], unique=False, schema='catalog')
    op.create_index(op.f('ix_catalog_artifacts_source_museum'), 'artifacts', ['source_museum'], unique=False, schema='catalog')
    op.create_index(op.f('ix_catalog_artifacts_tomb_temple_id'), 'artifacts', ['tomb_temple_id'], unique=False, schema='catalog')
    op.create_table('fuzzy_match_reviews',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('artifact_id', sa.String(), nullable=False),
    sa.Column('field', sa.String(), nullable=False),
    sa.Column('raw_value', sa.Text(), nullable=False),
    sa.Column('matched_id', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('reviewed_by', sa.String(), nullable=True),
    sa.Column('review_notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='catalog'
    )
    op.create_table('raw_brooklyn',
    sa.Column('object_id', sa.String(), nullable=False),
    sa.Column('data', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('object_id'),
    schema='catalog'
    )
    op.create_table('raw_harvard',
    sa.Column('object_id', sa.String(), nullable=False),
    sa.Column('data', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('object_id'),
    schema='catalog'
    )
    op.create_table('raw_met',
    sa.Column('object_id', sa.String(), nullable=False),
    sa.Column('data', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('object_id'),
    schema='catalog'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('raw_met', schema='catalog')
    op.drop_table('raw_harvard', schema='catalog')
    op.drop_table('raw_brooklyn', schema='catalog')
    op.drop_table('fuzzy_match_reviews', schema='catalog')
    op.drop_index(op.f('ix_catalog_artifacts_tomb_temple_id'), table_name='artifacts', schema='catalog')
    op.drop_index(op.f('ix_catalog_artifacts_source_museum'), table_name='artifacts', schema='catalog')
    op.drop_index(op.f('ix_catalog_artifacts_ruler_id'), table_name='artifacts', schema='catalog')
    op.drop_index(op.f('ix_catalog_artifacts_period'), table_name='artifacts', schema='catalog')
    op.drop_index(op.f('ix_catalog_artifacts_origin_site_id'), table_name='artifacts', schema='catalog')
    op.drop_index(op.f('ix_catalog_artifacts_object_type'), table_name='artifacts', schema='catalog')
    op.drop_index(op.f('ix_catalog_artifacts_excavation_id'), table_name='artifacts', schema='catalog')
    op.drop_index(op.f('ix_catalog_artifacts_dynasty'), table_name='artifacts', schema='catalog')
    op.drop_table('artifacts', schema='catalog')
    # ### end Alembic commands ###
